Make network plugin a variable to enable BYOCNI installs
isovalent/terraform-azure-aks pull request #1
Opened 2022-09-22 15:04 UTC by hhoover

this PR turns the network plugin into a variable so you can specify "none" for BYOCNI installs.

Also adds an example for how to use this module, in a separate commit if it's not needed.

2022-09-23 14:33 UTC, bmcustodio requested changes
Looking great but I have some requests 🙏🏼

2022-09-23 14:33 UTC, bmcustodio commented on variables.tf
> +  description = "The Network plugin used for Azure"
```suggestion
  description = "The network plugin to use (one of 'azure' or 'none')."
```

2022-09-23 14:33 UTC, bmcustodio commented on variables.tf
> +  default = "azure"
Nit: move up one line for alphabetical ordering.

2022-09-23 14:33 UTC, bmcustodio commented on README.md
> +| <a name="input_network_plugin"></a> [network\_plugin](#input\_network\_plugin) | The Network plugin used for Azure | `string` | `"azure"` | no |
Can you please re-run `make docs` after making the suggested change?

2022-09-23 14:33 UTC, bmcustodio commented on example/aks.tf
> +  source = "git@github.com:isovalent/terraform-k8s-cilium.git?ref=v1.0"
```suggestion
  source = "git::https://github.com/isovalent/terraform-k8s-cilium.git?ref=v1.0"
```

2022-09-23 14:33 UTC, bmcustodio commented on example/aks.tf
> +  ipsec_key               = var.ipsec_key
Missing some `terraform fmt` 😉

2022-09-23 14:33 UTC, bmcustodio commented on example/variables.tf
> +variable "subscription_id" {
Please remove this variable and the next one 🤐

2022-10-20 15:00 UTC, hhoover commented on variables.tf
> +  description = "The Network plugin used for Azure"
fixed

2022-10-20 15:02 UTC, hhoover commented on example/variables.tf
> +variable "subscription_id" {
this is an example, made to "just work".

2023-08-23 11:34 UTC, darox commented
@hhoover @bmcustodio shall I merge it and cut a new release?

2023-09-28 13:55 UTC, merged